config/routes.rb
Rails.application.routes.draw do

  get "activities",                 to: "activities#index",                   as: :activities
  get "activities/new",             to: "activities#new",                     as: :new_activity
  post "activities",                to: "activities#create"

  get "lists",                      to: "lists#index",                        as: :lists
  post "lists",                     to: "lists#create",                       as: :new_list
  get "lists/:id",                  to: "lists#show",                         as: :list
  delete "lists/:id",               to: "lists#destroy",                      as: :delete_list

  post "lists/:id/activity",        to: "listactivities#addactivity",         as: :add_activity
  patch "lists/:id/activity",       to: "listactivities#updateactivity",      as: :update_activity
  delete "lists/:id/activity",      to: "listactivities#destroyactivity",     as: :delete_activity
  get "listactivities/:id/edit",    to: "listactivities#edit",                as: :edit_activity
  get "listactivities/:id/show",    to: "listactivities#show",                as: :listactivity

  root "home#index"

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false }
  
  has_many :lists, through: :listactivities
  has_many :listactivities
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :listactivities
  has_many :activities, through: :listactivities
  
end

app/models/listactivity.rb
class Listactivity < ActiveRecord::Base
  belongs_to :activity
  belongs_to :list
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :lists
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  def index
    @activities = Activity.all
    @activity = Activity.new
  end

  def create
    @activity = Activity.new(params.require(:activity).permit(:name))
    if @activity.save
      redirect_to list_path(params[:list_id])
    else
      render :new
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @list = List.new
  end

end

app/controllers/listactivities_controller.rb
class ListactivitiesController < ApplicationController

  def edit
    @listactivity = Listactivity.find(params[:id])
    @levels = ["yes", "no", "maybe"]
  end

  def show
    @listactivity = Listactivity.find(params[:id])
  end

  def addactivity
    @list = List.find(params[:id])
    @listactivity = Listactivity.new
    @listactivity.list_id = @list.id
    @listactivity.activity_id = params[:activity_id]
    @listactivity.name = @listactivity.activity.name
    if @listactivity.save
      redirect_to edit_activity_path(id: @listactivity.id)
    else
      redirect_to list_path
    end
  end

  def updateactivity
    @listactivity = Listactivity.find(params[:id])
    if @listactivity.update(params.require(:listactivity).permit(:status, :notes))
      redirect_to list_path(id: @listactivity.list_id)
    else
      render :edit
    end
  end

  def destroyactivity
    @listactivity = Listactivity.find(params[:id])
    if @listactivity.destroy
      redirect_to list_path(id: @listactivity.list_id)
    else
      render :edit
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def create
    @list = List.new(params.require(:list).permit(:name))
    if @list.save
      redirect_to lists_path
    else
      render :index
    end
  end

  def show
    @activities = Activity.all
    @activity = Activity.new
    @list = List.find(params[:id])

    @yes_activities = Listactivity.where("status = ? AND list_id = ?","yes", params[:id])
    @no_activities = Listactivity.where("status = ? AND list_id = ?","no", params[:id])
    @maybe_activities = Listactivity.where("status = ? AND list_id = ?","maybe", params[:id])
    @nil_activities = Activity.where(status: nil)
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/index.html.erb
Activities:

<% @activities.each do |activity| %>
  <%= activity.name %>
<% end %>

Create New Activity

<%= form_for @activity do |f| %>
  <%= f.text_field :name, placeholder: "name" %>
  <%= f.submit %>
<% end %>

app/views/home/index.html.erb
This is the homepage.

Create a new Yes No Maybe List.
<%= form_for @list do |f| %>
  <%= f.text_field :name, placeholder: "List Name" %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YesNoMaybeList</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/listactivities/edit.html.erb
<%= @listactivity.activity.name %>

<%= form_for @listactivity,
                :url => update_activity_path(@listactivity,
                :id => params[:id]),
                :html => {method: :patch} do |f| %>
  <%= f.select(:status, @levels.map {|value| [value, value]}) %>
  <%= f.text_area :notes, placeholder: "Additional Thoughts + Ideas" %>
  <%= f.submit %>
<% end %>

app/views/listactivities/show.html.erb
<table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Status</th>
        <th>Notes + Thoughts</th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td><%= @listactivity.activity.name %></td>
          <td><%= @listactivity.status %></td>
          <td><%= @listactivity.notes %></td>
        </tr>
    </tbody>
  </table>
</div>


<%= link_to "Edit", edit_activity_path %>
<%= button_to "Delete", delete_activity_path, method: :delete %>
<%= link_to "Back to List", list_path(@listactivity.list.id) %>

app/views/lists/index.html.erb
<% @lists.each do |list| %>
  <%=link_to list.name, list_path(list.id) %>
<% end %>

app/views/lists/show.html.erb
<%= @list.name %>: Yes, No, Maybe List

<table>
  <thead>
    <th>Yes</th>
    <th>No</th>
    <th>Maybe</th>
  </thead>
  <tbody>
    <th>
      <% @yes_activities.each do |activity| %>
        <%=link_to activity.name, listactivity_path(id: activity.id) %><br>
      <% end %>
    </th>
    <th>
      <% @no_activities.each do |activity| %>
        <%=link_to activity.name, listactivity_path(id: activity.id) %><br>
      <% end %>
    </th>
    <th>
      <% @maybe_activities.each do |activity| %>
        <%=link_to activity.name, listactivity_path(id: activity.id) %><br>
      <% end %>
    </th>
  </tbody>
</table>

Select Activity:
<% @activities.each do |activity| %>
  <%= button_to activity.name, add_activity_path(@list.id, activity_id: activity.id), method: :post %>
<% end %>

Create Activity:
<%= form_for @activity do |f| %>
  <%= f.text_field :name, placeholder: "name" %>
  <%= hidden_field_tag(:list_id, @list.id) %>
  <%= f.submit %>
<% end %>